wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: logits_table._type
      5: 1
      6:
      - 1
    - 1: logits_table.path
      5: 1
      6:
      - 1
    - 1: logits_table.sha256
      5: 1
      6:
      - 1
    - 1: logits_table.size
      5: 1
      6:
      - 1
    - 1: logits_table.artifact_path
      5: 1
      6:
      - 1
    - 1: logits_table._latest_artifact_path
      5: 1
      6:
      - 1
    - 1: logits_table.ncols
      5: 1
      6:
      - 1
    - 1: logits_table.nrows
      5: 1
      6:
      - 1
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: train_acc
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    python_version: 3.9.5
    start_time: 1641738760
    t:
      1:
      - 1
      - 9
      2:
      - 1
      - 9
      3:
      - 7
      4: 3.9.5
      5: 0.12.9
      8:
      - 5
    visualize:
      logits:
        panel_config:
          fieldSettings:
            value: Height
          panelDefId: wandb/histogram/v0
          stringSettings:
            title: Predicted target distribution
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: logits_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
